spring.application.name=crack-server

# Server Port
server.port=7022

# Database Configuration
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/crackProject?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Mail Configuration (QQ Mail)
spring.mail.host=smtp.qq.com
spring.mail.port=587
spring.mail.username=2335696445@qq.com
spring.mail.password=ugqusqgdwciwdjia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# MyBatis Plus Configuration
mybatis-plus.type-aliases-package=com.bub6le.crackserver.entity
mybatis-plus.configuration.map-underscore-to-camel-case=false
mybatis-plus.global-config.db-config.id-type=auto

# Swagger Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=true
logging.level.com.bub6le.crackserver=DEBUG
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# File Upload Configuration
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
